#!/bin/bash
GRID_IDX=0 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=1 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=2 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=3 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=4 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=5 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=6 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=7 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=8 ./run_python.sh scripts/testing/hperturbs_cedar.py &
GRID_IDX=9 ./run_python.sh scripts/testing/hperturbs_cedar.py
# GRID_IDX=10 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=11 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=12 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=13 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=14 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=15 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=16 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=17 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=18 ./run_python.sh scripts/testing/hperturbs_cedar.py &
# GRID_IDX=19 ./run_python.sh scripts/testing/hperturbs_cedar.py &